// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuVx9KTstq90Osuwuvr19Vj4lL9rrbwtc',
    appId: '1:590103625739:web:bba56cc37598ab1a20c70e',
    messagingSenderId: '590103625739',
    projectId: 'raiseit-9fefc',
    authDomain: 'raiseit-9fefc.firebaseapp.com',
    databaseURL: 'https://raiseit-9fefc-default-rtdb.firebaseio.com',
    storageBucket: 'raiseit-9fefc.firebasestorage.app',
    measurementId: 'G-30T0GE5BRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWtBtTMSIsnYyJn9J_miGjMsgL5w-nrqI',
    appId: '1:590103625739:android:bbdaa6ef762e1f6920c70e',
    messagingSenderId: '590103625739',
    projectId: 'raiseit-9fefc',
    databaseURL: 'https://raiseit-9fefc-default-rtdb.firebaseio.com',
    storageBucket: 'raiseit-9fefc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0jxDFE5nQIL76mXGW9cdq24MA2jvRPuE',
    appId: '1:590103625739:ios:31ba546a2abc1a2120c70e',
    messagingSenderId: '590103625739',
    projectId: 'raiseit-9fefc',
    databaseURL: 'https://raiseit-9fefc-default-rtdb.firebaseio.com',
    storageBucket: 'raiseit-9fefc.firebasestorage.app',
    iosBundleId: 'com.example.raiseit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0jxDFE5nQIL76mXGW9cdq24MA2jvRPuE',
    appId: '1:590103625739:ios:31ba546a2abc1a2120c70e',
    messagingSenderId: '590103625739',
    projectId: 'raiseit-9fefc',
    databaseURL: 'https://raiseit-9fefc-default-rtdb.firebaseio.com',
    storageBucket: 'raiseit-9fefc.firebasestorage.app',
    iosBundleId: 'com.example.raiseit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuVx9KTstq90Osuwuvr19Vj4lL9rrbwtc',
    appId: '1:590103625739:web:0576350e59687f8320c70e',
    messagingSenderId: '590103625739',
    projectId: 'raiseit-9fefc',
    authDomain: 'raiseit-9fefc.firebaseapp.com',
    databaseURL: 'https://raiseit-9fefc-default-rtdb.firebaseio.com',
    storageBucket: 'raiseit-9fefc.firebasestorage.app',
    measurementId: 'G-8FZNWS06Y4',
  );
}
